# Generated by Django 4.2.1 on 2023-05-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profile_services", "0002_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="profile_services.post"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="profile_services.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="profile_services.post",
            ),
        ),
    ]
