# Generated by Django 4.2.1 on 2023-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profile_services",
            "0004_profile_followers_profile_following_alter_like_post",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="profile_services.tag"),
        ),
    ]
