# Generated by Django 4.0.4 on 2023-05-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_services', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profile_services.profile'),
            preserve_default=False,
        ),
    ]
