# Generated by Django 4.2.1 on 2023-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="lee", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
